### ISSUE TITLE
Read mysql credentials from prosody.cfg.lua

### ISSUE THREAD

**Issue by imolein** [mightyBroccoli/prosody_housekeeping#9]
Read the mysql credentials from prosody.cfg.lua. The benefit will be:
* credentials are not located in another plain text file
* avoiding that admins are writing their mysql root credentials into the config, out of laziness ;)

**Comment by mightyBroccoli** [comment]
in principal #10 should allow that. I tested it on my system and it worked properly, though I am not sure if that is the best way possible to achieve this result.
